//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zensar.Infrastructure.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPO_Entity
    {
        public int ID { get; set; }
        public string entity_id { get; set; }
        public string entity_name { get; set; }
        public string sanctions_descr { get; set; }
        public string sanctions_references { get; set; }
        public string company_country { get; set; }
    }
}
