//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zensar.Infrastructure.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPO_Person1
    {
        public int ID { get; set; }
        public string person_id { get; set; }
        public int date_year { get; set; }
        public string gender { get; set; }
        public string person_namex { get; set; }
        public string sanctions_descr { get; set; }
        public string sanctions_references { get; set; }
        public string country_code { get; set; }
    }
}
