//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zensar.Infrastructure.Data.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BPOEntities : DbContext
    {
        public BPOEntities()
            : base("name=BPOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BPO_Entity> BPO_Entity { get; set; }
        public DbSet<BPO_Person> BPO_Person { get; set; }
        public DbSet<BPO_Entity1> BPO_Entity1 { get; set; }
        public DbSet<BPO_Person1> BPO_Person1 { get; set; }
        public DbSet<BPOtransferStageLogtbl> BPOtransferStageLogtbls { get; set; }
    
        public virtual int EntityTransferPROC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EntityTransferPROC");
        }
    
        public virtual int PersonTransferPROC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PersonTransferPROC");
        }
    }
}
