//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zensar.Infrastructure.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPOtransferStageLogtbl
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ErrorStage { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorProbableCause { get; set; }
    }
}
